# Generated by Django 4.0.3 on 2022-03-10 01:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64, verbose_name='tag')),
            ],
            options={
                'db_table': 'bigtags',
            },
        ),
        migrations.CreateModel(
            name='FineTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128, verbose_name='tag')),
            ],
        ),
        migrations.CreateModel(
            name='Regist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.IntegerField(choices=[(1, 'incorrect'), (2, 'spam'), (3, 'violence'), (4, 'harassment')], verbose_name='報告')),
            ],
        ),
        migrations.CreateModel(
            name='ReportThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='賛同もしくは反論をコメント', verbose_name='コメント')),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('url', models.URLField(max_length=256, verbose_name='url')),
            ],
        ),
    ]
