# Generated by Django 4.0.3 on 2022-03-29 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BigTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('tag', models.CharField(max_length=64, verbose_name='tag')),
            ],
        ),
        migrations.CreateModel(
            name='FineTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('tag', models.CharField(max_length=128, verbose_name='tag')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assemble.bigtag', verbose_name='親タグ')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.IntegerField(choices=[(1, 'incorrect'), (2, 'spam'), (3, 'violence'), (4, 'harassment'), (5, 'old'), (6, 'note_need')], verbose_name='報告')),
                ('text', models.TextField(blank=True, verbose_name='報告文')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_by', to=settings.AUTH_USER_MODEL, verbose_name='報告者')),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('url', models.URLField(max_length=512, unique=True, verbose_name='url')),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='URL_FineTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assemble.finetag', verbose_name='詳細タグ')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assemble.url', verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='URL_BigTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assemble.bigtag', verbose_name='カテゴリタグ')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assemble.url', verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='ReportThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='賛同もしくは反論をコメント', verbose_name='コメント')),
                ('send_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_by', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('to_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_report', to='assemble.report', verbose_name='レポート')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assemble.url', verbose_name='url'),
        ),
        migrations.CreateModel(
            name='Regist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assemble.url', verbose_name='url')),
            ],
        ),
    ]
