# Generated by Django 4.0.3 on 2022-03-10 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assemble', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportthread',
            name='send_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_by', to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
        ),
        migrations.AddField(
            model_name='reportthread',
            name='to_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_report', to='assemble.report', verbose_name='レポート'),
        ),
        migrations.AddField(
            model_name='report',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assemble.url', verbose_name='url'),
        ),
        migrations.AddField(
            model_name='regist',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_by', to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
        ),
        migrations.AddField(
            model_name='finetag',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bigtag', to='assemble.bigtag', verbose_name='親タグ'),
        ),
        migrations.AddField(
            model_name='bigtag',
            name='url',
            field=models.ManyToManyField(related_name='tags', related_query_name='tag', to='assemble.url'),
        ),
    ]
