# Generated by Django 4.0.3 on 2022-03-10 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assemble', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regist',
            name='url',
            field=models.ManyToManyField(related_name='registers', related_query_name='register', to='assemble.url'),
        ),
        migrations.AddField(
            model_name='report',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_by', to=settings.AUTH_USER_MODEL, verbose_name='報告者'),
        ),
        migrations.AddField(
            model_name='report',
            name='text',
            field=models.TextField(blank=True, verbose_name='報告文'),
        ),
        migrations.AlterField(
            model_name='bigtag',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='finetag',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.IntegerField(choices=[(1, 'incorrect'), (2, 'spam'), (3, 'violence'), (4, 'harassment'), (5, 'old'), (6, 'note_need')], verbose_name='報告'),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(max_length=512, unique=True, verbose_name='url'),
        ),
    ]
