# Generated by Django 4.0.3 on 2022-03-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemble', '0003_regist_url_report_reported_by_report_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigtag',
            name='url',
            field=models.ManyToManyField(null=True, related_name='tags', related_query_name='tag', to='assemble.url'),
        ),
    ]
