# Generated by Django 4.0.3 on 2022-03-10 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assemble', '0004_alter_bigtag_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='finetag',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assemble.url', verbose_name='URL'),
        ),
        migrations.RemoveField(
            model_name='bigtag',
            name='url',
        ),
        migrations.AddField(
            model_name='bigtag',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assemble.url', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='finetag',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assemble.bigtag', verbose_name='親タグ'),
        ),
        migrations.AlterModelTable(
            name='bigtag',
            table=None,
        ),
    ]
