# Generated by Django 4.0.3 on 2022-03-10 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assemble', '0005_finetag_url_remove_bigtag_url_bigtag_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigtag',
            name='url',
        ),
        migrations.RemoveField(
            model_name='finetag',
            name='url',
        ),
        migrations.AlterField(
            model_name='regist',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
        ),
        migrations.CreateModel(
            name='URL_FineTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assemble.finetag', verbose_name='詳細タグ')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assemble.url', verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='URL_BigTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assemble.bigtag', verbose_name='カテゴリタグ')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assemble.url', verbose_name='url')),
            ],
        ),
    ]
