# Generated by Django 4.0.3 on 2022-03-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemble', '0006_remove_bigtag_url_remove_finetag_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='title',
            field=models.CharField(blank=True, max_length=128, verbose_name='title'),
        ),
    ]
