# Generated by Django 4.0.3 on 2022-03-22 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assemble', '0007_url_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regist',
            name='url',
        ),
        migrations.AddField(
            model_name='regist',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assemble.url', verbose_name='url'),
        ),
    ]
